# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com


# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

# Define the pipeline for building and releasing your Go application
project_name: vapusctl
env:
  - CGO_ENABLED=0
  - VAPUSDATA_VERSION={{ .Version }}
  - VAPUSDATA_LDFLAGS=-s -w
  # - TAG=main
  # - COSIGN_KEY=cosisfgsadfgasdfgsdfgsdf
  # - CONTAINER_REGISTRY=ghcr.io/anekam/
  # - OCI_IMAGE=vapusdata/webapp
report_sizes: true
before:
  hooks:
    - go mod tidy
    - go mod vendor
dist: dist-bin
builds:
  - binary: vapusctl
    id: vapusctl
    main: "."
    no_unique_dist_dir: true
    goos:
      # - linux
      - darwin
      # - windows
    goarch:
      # - amd64
      - arm64
    ldflags:
      - "{{ .Env.VAPUSDATA_LDFLAGS }}"
      - "-X github.com/vapusdata-oss/aistudio/app/src/cli/version.Version={{ .Env.TAG }}"
      - "-X main.Version={{ .Env.TAG }}"
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # files:
    #   - README.md
    #   - LICENSE
    wrap_in_directory: true
# dockers:
#   - dockerfile: Dockerfile
#     ids:
#       - vapusctl
#     image_templates:
#       - "{{ .Env.CONTAINER_REGISTRY }}{{ .Env.OCI_IMAGE }}:{{ .Env.TAG }}"
#       - "{{ .Env.CONTAINER_REGISTRY }}{{ .Env.OCI_IMAGE }}:latest"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Env.TAG }}_checksum.txt"
sboms:
  - id: binary-sbom
    artifacts: binary
release:
  make_latest: true
  # github:
  #   owner: vikrant@vapusdata.com
  #   name: github.com/vapusdata-oss/aistudio

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - cmd: cosign
    id: vapusctl-signs
    artifacts: all
    stdin: ""
    args:
      - sign-blob
      - "--key=env://COSIGN_KEY"
      - "--yes"
      - "--output-signature=${signature}"
      - "${artifact}"

# blobs:
#   - provider: gs
#     bucket: vapusdata-public/vapusctl