apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vapusdata.globalSecrets.backend.secretStore }}
type: Opaque
stringData:
  {{ .Values.vapusdata.globalSecrets.backend.secretStoreFileName }}: |-
  {{ if .Values.app.dev }}
    {{ .Values.devSecretStore | b64enc | toYaml | nindent 4 }}s
  {{ else }}
    {{ .Values.secretStore | toYaml | nindent 4 }}
  {{ end }}