apiVersion: v1
data:
  tls.crt: {{ .Values.tlsCert.cert }}
  tls.key: {{ .Values.tlsCert.key }}
kind: Secret
metadata:
  name: {{ .Values.vapusdata.globalSecrets.certs.tlsSecret }}
type: kubernetes.io/tls