# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/vapusai-studio/v1alpha1/aiguardrails.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'protos/vapusai-studio/v1alpha1/aiguardrails.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protos.models.v1alpha1 import vapusai_pb2 as protos_dot_models_dot_v1alpha1_dot_vapusai__pb2
from protos.models.v1alpha1 import common_pb2 as protos_dot_models_dot_v1alpha1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1protos/vapusai-studio/v1alpha1/aiguardrails.proto\x12\x10vapusai.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a$protos/models/v1alpha1/vapusai.proto\x1a#protos/models/v1alpha1/common.proto\"\x81\x01\n\x12GuardrailsResponse\x12\x34\n\x07\x64m_resp\x18\x01 \x01(\x0b\x32\x1b.models.v1alpha1.DMResponseR\x06\x64mResp\x12\x35\n\x06output\x18\x02 \x03(\x0b\x32\x1d.models.v1alpha1.AIGuardrailsR\x06output\"\x90\x01\n\x18GuardrailsManagerRequest\x12\x41\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32).vapusai.v1alpha1.VapusAIGuardrailsActionR\x06\x61\x63tion\x12\x31\n\x04spec\x18\x02 \x01(\x0b\x32\x1d.models.v1alpha1.AIGuardrailsR\x04spec\"}\n\x17GuardrailsGetterRequest\x12!\n\x0cguardrail_id\x18\x01 \x01(\tR\x0bguardrailId\x12?\n\x0csearch_param\x18\x02 \x01(\x0b\x32\x1c.models.v1alpha1.SearchParamR\x0bsearchParam*|\n\x17VapusAIGuardrailsAction\x12\x1c\n\x18INVALID_GUARDRAIL_ACTION\x10\x00\x12\x17\n\x13\x43ONFIGURE_GUARDRAIL\x10\x01\x12\x15\n\x11\x41RCHIVE_GUARDRAIL\x10\x02\x12\x13\n\x0fPATCH_GUARDRAIL\x10\x03\x32\x9e\x02\n\x0c\x41IGuardrails\x12\x80\x01\n\x07Manager\x12*.vapusai.v1alpha1.GuardrailsManagerRequest\x1a$.vapusai.v1alpha1.GuardrailsResponse\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/api/v1alpha1/guardrails:\x01*\x12\x8a\x01\n\x06Getter\x12).vapusai.v1alpha1.GuardrailsGetterRequest\x1a$.vapusai.v1alpha1.GuardrailsResponse\"/\x82\xd3\xe4\x93\x02)\x12\'/api/v1alpha1/guardrails/{guardrail_id}B\xc1\x01\n\x14\x63om.vapusai.v1alpha1B\x11\x41iguardrailsProtoP\x01Z5github.com/vapusdata-oss/apis/protos/vapusai/v1alpha1\xa2\x02\x03VXX\xaa\x02\x10Vapusai.V1alpha1\xca\x02\x10Vapusai\\V1alpha1\xe2\x02\x1cVapusai\\V1alpha1\\GPBMetadata\xea\x02\x11Vapusai::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vapusai_studio.v1alpha1.aiguardrails_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.vapusai.v1alpha1B\021AiguardrailsProtoP\001Z5github.com/vapusdata-oss/apis/protos/vapusai/v1alpha1\242\002\003VXX\252\002\020Vapusai.V1alpha1\312\002\020Vapusai\\V1alpha1\342\002\034Vapusai\\V1alpha1\\GPBMetadata\352\002\021Vapusai::V1alpha1'
  _globals['_AIGUARDRAILS'].methods_by_name['Manager']._loaded_options = None
  _globals['_AIGUARDRAILS'].methods_by_name['Manager']._serialized_options = b'\202\323\344\223\002\035\"\030/api/v1alpha1/guardrails:\001*'
  _globals['_AIGUARDRAILS'].methods_by_name['Getter']._loaded_options = None
  _globals['_AIGUARDRAILS'].methods_by_name['Getter']._serialized_options = b'\202\323\344\223\002)\022\'/api/v1alpha1/guardrails/{guardrail_id}'
  _globals['_VAPUSAIGUARDRAILSACTION']._serialized_start=582
  _globals['_VAPUSAIGUARDRAILSACTION']._serialized_end=706
  _globals['_GUARDRAILSRESPONSE']._serialized_start=177
  _globals['_GUARDRAILSRESPONSE']._serialized_end=306
  _globals['_GUARDRAILSMANAGERREQUEST']._serialized_start=309
  _globals['_GUARDRAILSMANAGERREQUEST']._serialized_end=453
  _globals['_GUARDRAILSGETTERREQUEST']._serialized_start=455
  _globals['_GUARDRAILSGETTERREQUEST']._serialized_end=580
  _globals['_AIGUARDRAILS']._serialized_start=709
  _globals['_AIGUARDRAILS']._serialized_end=995
# @@protoc_insertion_point(module_scope)
