# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/vapusai-studio/v1alpha1/aiprompts.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'protos/vapusai-studio/v1alpha1/aiprompts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protos.models.v1alpha1 import vapusai_pb2 as protos_dot_models_dot_v1alpha1_dot_vapusai__pb2
from protos.models.v1alpha1 import common_pb2 as protos_dot_models_dot_v1alpha1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protos/vapusai-studio/v1alpha1/aiprompts.proto\x12\x10vapusai.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a$protos/models/v1alpha1/vapusai.proto\x1a#protos/models/v1alpha1/common.proto\"\x87\x01\n\x14PromptManagerRequest\x12;\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32#.vapusai.v1alpha1.PromptAgentActionR\x06\x61\x63tion\x12\x32\n\x04spec\x18\x02 \x03(\x0b\x32\x1e.models.v1alpha1.AIModelPromptR\x04spec\"s\n\x13PromptGetterRequest\x12\x1b\n\tprompt_id\x18\x01 \x01(\tR\x08promptId\x12?\n\x0csearch_param\x18\x02 \x01(\x0b\x32\x1c.models.v1alpha1.SearchParamR\x0bsearchParam\"~\n\x0ePromptResponse\x12\x34\n\x07\x64m_resp\x18\x01 \x01(\x0b\x32\x1b.models.v1alpha1.DMResponseR\x06\x64mResp\x12\x36\n\x06output\x18\x02 \x03(\x0b\x32\x1e.models.v1alpha1.AIModelPromptR\x06output*j\n\x11PromptAgentAction\x12\x19\n\x15INVALID_PROMPT_ACTION\x10\x00\x12\x14\n\x10\x43ONFIGURE_PROMPT\x10\x01\x12\x12\n\x0e\x41RCHIVE_PROMPT\x10\x02\x12\x10\n\x0cPATCH_PROMPT\x10\x03\x32\x80\x02\n\tAIPrompts\x12u\n\x07Manager\x12&.vapusai.v1alpha1.PromptManagerRequest\x1a .vapusai.v1alpha1.PromptResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x15/api/v1alpha1/prompts:\x01*\x12|\n\x06Getter\x12%.vapusai.v1alpha1.PromptGetterRequest\x1a .vapusai.v1alpha1.PromptResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1alpha1/prompts/{prompt_id}B\xbe\x01\n\x14\x63om.vapusai.v1alpha1B\x0e\x41ipromptsProtoP\x01Z5github.com/vapusdata-oss/apis/protos/vapusai/v1alpha1\xa2\x02\x03VXX\xaa\x02\x10Vapusai.V1alpha1\xca\x02\x10Vapusai\\V1alpha1\xe2\x02\x1cVapusai\\V1alpha1\\GPBMetadata\xea\x02\x11Vapusai::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vapusai_studio.v1alpha1.aiprompts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.vapusai.v1alpha1B\016AipromptsProtoP\001Z5github.com/vapusdata-oss/apis/protos/vapusai/v1alpha1\242\002\003VXX\252\002\020Vapusai.V1alpha1\312\002\020Vapusai\\V1alpha1\342\002\034Vapusai\\V1alpha1\\GPBMetadata\352\002\021Vapusai::V1alpha1'
  _globals['_AIPROMPTS'].methods_by_name['Manager']._loaded_options = None
  _globals['_AIPROMPTS'].methods_by_name['Manager']._serialized_options = b'\202\323\344\223\002\032\"\025/api/v1alpha1/prompts:\001*'
  _globals['_AIPROMPTS'].methods_by_name['Getter']._loaded_options = None
  _globals['_AIPROMPTS'].methods_by_name['Getter']._serialized_options = b'\202\323\344\223\002#\022!/api/v1alpha1/prompts/{prompt_id}'
  _globals['_PROMPTAGENTACTION']._serialized_start=556
  _globals['_PROMPTAGENTACTION']._serialized_end=662
  _globals['_PROMPTMANAGERREQUEST']._serialized_start=174
  _globals['_PROMPTMANAGERREQUEST']._serialized_end=309
  _globals['_PROMPTGETTERREQUEST']._serialized_start=311
  _globals['_PROMPTGETTERREQUEST']._serialized_end=426
  _globals['_PROMPTRESPONSE']._serialized_start=428
  _globals['_PROMPTRESPONSE']._serialized_end=554
  _globals['_AIPROMPTS']._serialized_start=665
  _globals['_AIPROMPTS']._serialized_end=921
# @@protoc_insertion_point(module_scope)
