# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.models.v1alpha1 import common_pb2 as protos_dot_models_dot_v1alpha1_dot_common__pb2
from protos.vapusai_studio.v1alpha1 import users_pb2 as protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2


class UserManagementServiceStub(object):
    """*
    The UserManagementService is the service interface for managing users across vapusai services.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AccessTokenInterface = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/AccessTokenInterface',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenInterfaceRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
                _registered_method=True)
        self.RegisterUser = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/RegisterUser',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
                _registered_method=True)
        self.UserManager = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/UserManager',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserManagerRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.FromString,
                _registered_method=True)
        self.RefreshTokenManager = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/RefreshTokenManager',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenManagerRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.RefreshTokenGetter = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/RefreshTokenGetter',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenGetterRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.UserGetter = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/UserGetter',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserGetterRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.FromString,
                _registered_method=True)
        self.AuthzManager = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/AuthzManager',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzManagerRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.FromString,
                _registered_method=True)
        self.AuthzGetter = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/AuthzGetter',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzGetterRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.FromString,
                _registered_method=True)
        self.LoginHandler = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/LoginHandler',
                request_serializer=protos_dot_models_dot_v1alpha1_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginHandlerResponse.FromString,
                _registered_method=True)
        self.LoginCallback = channel.unary_unary(
                '/vapusai.v1alpha1.UserManagementService/LoginCallback',
                request_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginCallBackRequest.SerializeToString,
                response_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
                _registered_method=True)


class UserManagementServiceServicer(object):
    """*
    The UserManagementService is the service interface for managing users across vapusai services.
    """

    def AccessTokenInterface(self, request, context):
        """*
        Generates a access token for the given user.
        @param {AccessTokenInterfaceRequest} request - The request object.
        @returns {AccessTokenResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserManager(self, request, context):
        """*
        Manages user operations.
        @param {UserManagerRequest} request - The request object.
        @returns {UserResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshTokenManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshTokenGetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserGetter(self, request, context):
        """*
        Retrieves user information.
        @param {UserGetterRequest} request - The request object.
        @returns {UserResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthzManager(self, request, context):
        """*
        Manages authorization operations.
        @param {AuthzManagerRequest} request - The request object.
        @returns {AuthzResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthzGetter(self, request, context):
        """*
        Retrieves authorization information.
        @param {AuthzGetterRequest} request - The request object.
        @returns {AuthzResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginHandler(self, request, context):
        """*
        Handles login requests.
        @param {models.v1alpha1.EmptyRequest} request - The request object.
        @returns {LoginHandlerResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginCallback(self, request, context):
        """*
        Handles login callbacks.
        @param {LoginCallBackRequest} request - The request object.
        @returns {AccessTokenResponse} The response object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AccessTokenInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessTokenInterface,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenInterfaceRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RegisterUserRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.SerializeToString,
            ),
            'UserManager': grpc.unary_unary_rpc_method_handler(
                    servicer.UserManager,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserManagerRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.SerializeToString,
            ),
            'RefreshTokenManager': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshTokenManager,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenManagerRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'RefreshTokenGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshTokenGetter,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenGetterRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'UserGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.UserGetter,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserGetterRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.SerializeToString,
            ),
            'AuthzManager': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthzManager,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzManagerRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.SerializeToString,
            ),
            'AuthzGetter': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthzGetter,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzGetterRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.SerializeToString,
            ),
            'LoginHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginHandler,
                    request_deserializer=protos_dot_models_dot_v1alpha1_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginHandlerResponse.SerializeToString,
            ),
            'LoginCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginCallback,
                    request_deserializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginCallBackRequest.FromString,
                    response_serializer=protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vapusai.v1alpha1.UserManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vapusai.v1alpha1.UserManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserManagementService(object):
    """*
    The UserManagementService is the service interface for managing users across vapusai services.
    """

    @staticmethod
    def AccessTokenInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/AccessTokenInterface',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenInterfaceRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/RegisterUser',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RegisterUserRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/UserManager',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserManagerRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshTokenManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/RefreshTokenManager',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenManagerRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshTokenGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/RefreshTokenGetter',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenGetterRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/UserGetter',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserGetterRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthzManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/AuthzManager',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzManagerRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthzGetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/AuthzGetter',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzGetterRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AuthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/LoginHandler',
            protos_dot_models_dot_v1alpha1_dot_common__pb2.EmptyRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginHandlerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vapusai.v1alpha1.UserManagementService/LoginCallback',
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.LoginCallBackRequest.SerializeToString,
            protos_dot_vapusai__studio_dot_v1alpha1_dot_users__pb2.AccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
