// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: protos/vapusai-studio/v1alpha1/aimodels.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIModels_Manager_FullMethodName = "/vapusai.v1alpha1.AIModels/Manager"
	AIModels_Getter_FullMethodName  = "/vapusai.v1alpha1.AIModels/Getter"
)

// AIModelsClient is the client API for AIModels service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIModelsClient interface {
	// *
	// Retrieves a data worker deployment.
	// @param {Manager} request - The request object containing the AI model node configurator.
	// @returns {AIModelNodeResponse} The response object containing the AI model node configurator.
	Manager(ctx context.Context, in *AIModelNodeConfiguratorRequest, opts ...grpc.CallOption) (*AIModelNodeResponse, error)
	// *
	// Retrieves a data worker deployment.
	// @param {AIModelNodeGetterRequest} request - The request object containing the AI model node getter.
	// @returns {AIModelNodeResponse} The response object containing the AI model node getter.
	Getter(ctx context.Context, in *AIModelNodeGetterRequest, opts ...grpc.CallOption) (*AIModelNodeResponse, error)
}

type aIModelsClient struct {
	cc grpc.ClientConnInterface
}

func NewAIModelsClient(cc grpc.ClientConnInterface) AIModelsClient {
	return &aIModelsClient{cc}
}

func (c *aIModelsClient) Manager(ctx context.Context, in *AIModelNodeConfiguratorRequest, opts ...grpc.CallOption) (*AIModelNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIModelNodeResponse)
	err := c.cc.Invoke(ctx, AIModels_Manager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModelsClient) Getter(ctx context.Context, in *AIModelNodeGetterRequest, opts ...grpc.CallOption) (*AIModelNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIModelNodeResponse)
	err := c.cc.Invoke(ctx, AIModels_Getter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIModelsServer is the server API for AIModels service.
// All implementations must embed UnimplementedAIModelsServer
// for forward compatibility
type AIModelsServer interface {
	// *
	// Retrieves a data worker deployment.
	// @param {Manager} request - The request object containing the AI model node configurator.
	// @returns {AIModelNodeResponse} The response object containing the AI model node configurator.
	Manager(context.Context, *AIModelNodeConfiguratorRequest) (*AIModelNodeResponse, error)
	// *
	// Retrieves a data worker deployment.
	// @param {AIModelNodeGetterRequest} request - The request object containing the AI model node getter.
	// @returns {AIModelNodeResponse} The response object containing the AI model node getter.
	Getter(context.Context, *AIModelNodeGetterRequest) (*AIModelNodeResponse, error)
	mustEmbedUnimplementedAIModelsServer()
}

// UnimplementedAIModelsServer must be embedded to have forward compatible implementations.
type UnimplementedAIModelsServer struct {
}

func (UnimplementedAIModelsServer) Manager(context.Context, *AIModelNodeConfiguratorRequest) (*AIModelNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Manager not implemented")
}
func (UnimplementedAIModelsServer) Getter(context.Context, *AIModelNodeGetterRequest) (*AIModelNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Getter not implemented")
}
func (UnimplementedAIModelsServer) mustEmbedUnimplementedAIModelsServer() {}

// UnsafeAIModelsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIModelsServer will
// result in compilation errors.
type UnsafeAIModelsServer interface {
	mustEmbedUnimplementedAIModelsServer()
}

func RegisterAIModelsServer(s grpc.ServiceRegistrar, srv AIModelsServer) {
	s.RegisterService(&AIModels_ServiceDesc, srv)
}

func _AIModels_Manager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIModelNodeConfiguratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelsServer).Manager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModels_Manager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelsServer).Manager(ctx, req.(*AIModelNodeConfiguratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModels_Getter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIModelNodeGetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModelsServer).Getter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModels_Getter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModelsServer).Getter(ctx, req.(*AIModelNodeGetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIModels_ServiceDesc is the grpc.ServiceDesc for AIModels service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIModels_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vapusai.v1alpha1.AIModels",
	HandlerType: (*AIModelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Manager",
			Handler:    _AIModels_Manager_Handler,
		},
		{
			MethodName: "Getter",
			Handler:    _AIModels_Getter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/vapusai-studio/v1alpha1/aimodels.proto",
}
