name: Platform service workflows

on:
  # push:
  #   paths:
  #     - 'app/src/platform/**'
  workflow_call:
    inputs:
      oci-registry:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      oci-username:
        required: true
      oci-password:
        required: true
      signing-key:
        required: true
      signing-password:
        required: true
jobs:
  # platform-svc-pre-release:
  #   name: Pre release checks for platform service like lint, and sec checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23

  #     - name: Install Golangci-lint
  #       working-directory: app/src/platform
  #       run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      
  #     - name : Install go sec
  #       working-directory: app/src/platform
  #       run: go install github.com/securego/gosec/v2/cmd/gosec@latest

  #     - name: Lint for internals package
  #       continue-on-error: true # To Be Removed
  #       working-directory: internals
  #       run: |
  #         go mod tidy
  #         go mod vendor
  #         golangci-lint run --out-format checkstyle:/tmp/internals-lint-reports.json
  #     - name: Sec check for internals package
  #       continue-on-error: true # To Be Removed
  #       working-directory: internals
  #       run: |
  #         go mod tidy
  #         go mod vendor
  #         gosec -fmt=json -out=/tmp/internals-sec-reports.json ./...
  #     - name: Lint check for platform service
  #       continue-on-error: true # To Be Removed
  #       working-directory: app/src/platform
  #       run: |
  #         golangci-lint run --out-format checkstyle:/tmp/platform-lint-reports.json
  #     - name: Sec check for platform service
  #       continue-on-error: true # To Be Removed
  #       working-directory: app/src/platform
  #       run: |
  #         gosec -fmt=json -out=/tmp/platform-sec-reports.json ./... 
  #     - name: Uploading pre-release output as artifacts
  #       id: upload-artifacts-golang
  #       uses: actions/upload-artifact@v4.3.6
  #       with:
  #         name: platform-pre-release-artifacts
  #         path: /tmp/*-reports*  
  platform-svc-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build and Release Platform service
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for goreleaser to upload the release assets
      packages: write # to push worker images
      pull-requests: write
      id-token: write
      attestations: write
    env:
      SIGNING_KEY: ${{ secrets.signing-key }}
      SIGNING_PASSWORD: ${{ secrets.signing-password }}
      OCI_REGISTRY: ${{ inputs.oci-registry }}
      OCI_USERNAME: ${{ secrets.oci-username }}
      OCI_PASSWORD: ${{ secrets.oci-password }}
      OCI_IMAGE: /vapusdata-ecosystem/platform
      ARTIFACT_PREFIX: platform
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.9.0
        with:
          syft-version: 'v1.17.0'
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: Check cosign install!
        run: cosign version

      - name: Extract env vars
        id: extract_env_vars
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
      
      - name: Generate code with Buf
        working-directory: apis
        run: buf generate

      - name: Log in to Google Artifact Registry
        run: |
          docker login -u "${{ env.OCI_USERNAME }}" --password "${{ env.OCI_PASSWORD }}" "${{ env.OCI_REGISTRY }}"

      - name: Release Golang Services
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          workdir: app/src/platform
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER_REGISTRY: ${{ env.OCI_REGISTRY }}
          TAG: ${{ env.TAG_NAME }}
          COMMIT_TAG: ${{ env.GIT_COMMIT }}
          OCI_IMAGE: ${{ env.OCI_IMAGE }}
      - name: Get OCI Artifact Digest and files
        id: get-digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ env.OCI_REGISTRY }}${{ env.OCI_IMAGE }}:${{ env.TAG_NAME }}" | awk -F '@' '{print $2}')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "$DIGEST" > platform-digest.txt
          echo "${{ env.TAG_NAME }}" > platform-tag.txt

      - name: Generate cyclonedx SBOMs for platform OCI image ${{ env.TAG_NAME }}
        uses: anchore/sbom-action@v0.16.0
        with:
          image: ${{ env.OCI_REGISTRY }}${{ env.OCI_IMAGE }}:${{ env.TAG_NAME }}
          format: cyclonedx-json
          artifact-name: ${{ env.ARTIFACT_PREFIX }}-${{ env.TAG_NAME }}.cyclonedx.json
          output-file: /tmp/sbom.${{ env.ARTIFACT_PREFIX }}.cyclonedx.json
          upload-artifact: false

      - name: Uploading SBOMs
        id: upload-artifacts-golang
        uses: actions/upload-artifact@v4.3.6
        with:
          name: platform-SBOM-artifacts
          path: /tmp/sbom*  

      - name: Sign OCI Image
        env:
          COSIGN_KEY: ${{ env.SIGNING_KEY }}
          COSIGN_PASSWORD: ${{ env.SIGNING_PASSWORD }}
        run: |
          cosign sign --key env://COSIGN_KEY --upload=true ${{ env.OCI_REGISTRY }}${{ env.OCI_IMAGE }}@${{ steps.get-digest.outputs.digest }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: platform-digest-artifacts
          path: platform-digest.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: platform-tag-artifacts
          path: platform-tag.txt
      - uses: actions/attest-build-provenance/predicate@9ff3713ef183e028b07415e8a740b634c054a663 # predicate@1.1.1
        id: generate-build-provenance-predicate
        name: Generate build provenance predicate

      - name: Platform SVC attestation
        uses: actions/attest-build-provenance@v1
        id: platform-attestation
        with:
          subject-name: ${{ env.OCI_REGISTRY }}${{ env.OCI_IMAGE }}
          subject-digest: ${{ steps.get-digest.outputs.digest }}
          push-to-registry: true
          predicate-type: ${{ steps.generate-build-provenance-predicate.outputs.predicate-type }}
          predicate: ${{ steps.generate-build-provenance-predicate.outputs.predicate }}
          github-token: ${{ secrets.GITHUB_TOKEN }}   
